name : Deploy no kuerbenetes
on:
    workflow_call:
        inputs:
            environment-name:
                type: string
                required: true
            environment-url:
                type: string
                required: true
jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        environment: 
            name: ${{ github.event.inputs.environment-name }}
            url: ${{ github.event.inputs.environment-url }}
        steps:
            - name: Obtendo código do projeto
              uses: actions/checkout@v4

            - name: Donfiguração k8s contexto
              uses: Azure/k8s-set-context@v4
              with:
                method: kubeconfig
                kubeconfig: ${{ secrets.K8S_CONFIG }}

            - name: Deploy no k8s
              uses: Azure/k8s-deploy@v5
              with:
                manifests: |
                    k8s/deployment.yaml
                images: |
                    ${{ secrets.DOCKER_USERNAME }}/review-filmes-master:v${{ github.run_number }}