name : CI/CD
run-name: CI/CD exucutada por ${{ github.actor }} em ${{ github.run_number }}
on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    build:
        name: Executando build
        runs-on: ubuntu-latest
        steps:
            - name: Obtendo código do projeto
              uses: actions/checkout@v4
            - name: Setup dotnet
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: 8.0.300
            - name: Executando dotnet build
              working-directory: ./src
              run: dotnet build Review-Filmes.sln
    testes:
        needs: build
        uses: casoftsolutions/master-ci-cd/.github/workflows/teste.yml@main

    release:
        name: Criando a release
        runs-on: ubuntu-latest
        needs: testes
        steps:
            - name: Obtendo código do projeto
              uses: actions/checkout@v4
            - name: Efetuando login no Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Build da imagem Docker
              uses: docker/build-push-action@v3
              with:
                context: ./src
                file: ./src/Review-Filmes.Web/Dockerfile
                push: true
                tags: |
                    ${{ secrets.DOCKER_USERNAME }}/review-filmes-master:latest
                    ${{ secrets.DOCKER_USERNAME }}/review-filmes-master:v${{ github.run_number }}